sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zj93991102
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMN2wSpVK1j8JK5RiUt
    access-key-secret:
    bucket-name: sky-agar
  redis:
    host: localhost
    port: 6379
    password: zj93991102
    database: 1
  wechat:
    appid: wx6a3bd4c4671c3987
    secret:

